### ISSUE TITLE
Bunyan version dependency

### ISSUE THREAD

**Issue by nycjoker** [ericelliott/bunyan-request-logger#10]
What's the plan to upgrade bunyan version dependency? Currently, bunyan is maintained as a package dependency. Bunyan release is currently at version 1.3.4.

**Comment by ericelliott** [comment]
Send a pull request? =)

**Comment by nycjoker** [comment]
Done.

**Comment by nycjoker** [comment]
Please review the pull request and merge when you get a chance.

**Comment by nycjoker** [comment]
Great! Thanks.

**Comment by ericelliott** [comment]
Thank you.
