### ISSUE TITLE
responseTime seems not to work correctly.

### ISSUE THREAD

**Issue by mattii** [ericelliott/bunyan-request-logger#14]
Hi Eric,
thanks for that module, I came across it reading your book *Programming JavaScript Applications*. But in a first test, it seems not to calculate the correct response time. On a password route (working with your *credentials* module) for example, it measures only ~20ms, while the response time is nearly 900ms due to security reasons.

I checked the code and it seems like the module is measuring the time until the *request* is finished, right before the *response* begins. If I changed the event from `req.on('end', ...)` to `res.on('finish', ...)`, it measures proper response times. 

Another strategy could be the use of the [on-headers](https://github.com/jshttp/on-headers) module. It adds an event for the first writing of a header by monkey-patching response's `writeHead`. But in that moment, there won't be any header to be logged.

I would prefer the response-finish event, as it provides information about header-fields an measures the time in the moment the response really has been finished.

What option would you prefer? I could make a pull-request to fix it.

**Comment by ericelliott** [comment]
I would consider `res.on('finish'...`

**Comment by mattii** [comment]
Sorry for the delay! The problem is not as obvious as I thought in the first moment and I didn't have the time to take a thorough look at it before. 

After writing a test with a slow route to test the proper response time logging, I couldn't make it fail with the current `req.on('end'...)` implementation. It only fails in combination with the [body-parser](https://github.com/expressjs/body-parser) middleware and a `.post` request.

`res.on('finish', ...)` makes the test pass again, but it feels strange to add *body-parser* to the tests, just to make the current implementation fail. What do you think on this? Should I remove *body-parser* before I pull request?

**Comment by ericelliott** [comment]
I believe `res.on('finish', ...)` is the better option. Don't worry about `body-parser`.
