### ISSUE TITLE
How to use log.gif

### ISSUE THREAD

**Issue by amelon** [ericelliott/bunyan-request-logger#15]
Hi,

I miss something with `log.gif` as I don't understand how to send info to server.

I used something like that, is it ok?

````js
    function logMsg(msg) {
      var img = document.createElement('img');
      var bodyArr = document.getElementsByTagName('body');
      img.src = '/log.gif?msg=' + msg;
      bodyArr[0].appendChild(img);
    }
````

I think there is a bug in `log.route`. `data` is assigned to `req.params` but `data` is never used:

````js
      return function pixel(req, res) {
        var data;

        if (settings.logParams && req.params) {
          data = assign({}, req.params, {
            requestId: req.requestId
          });
          log.info(req.params);
        }
       ...
      }
````

**Comment by ericelliott** [comment]
If you'd like to add a decent test for pixel data logging (including the presence of request ID), I'll gladly take a PR and bump the version.

**Comment by amelon** [comment]
thanks for your reply.

Actually, I better understand your example in `express-error-handler`

````
app.get('/log', noCache,
    function logHandler(req, res) {

  // Since all requests are automatically logged,
  // all you need to do is send the response:
  res.status(200).end();
});
````

I gonna try to make a decent test this week.

**Comment by ericelliott** [comment]
=)

**Comment by amelon** [comment]
Hi, I've just changed test file.
Is it ok now?

**Comment by zjr** [comment]
PR got merged for the bug fix related to this but version was never bumped.  ¯\_(ツ)_/¯

**Comment by zjr** [comment]
Also, why `req.params` and not `req.query`? maybe that ought to be a separate issue.

**Comment by ericelliott** [comment]
Published latest.
