### ISSUE TITLE
Switch to lodash

### ISSUE THREAD

**Issue by jdalton** [ericelliott/bunyan-request-logger#2]
I noticed a few of your projects are deping on `mout` while you also use grunt.
You can remove the mout dep and just use `grunt.util._` for grunt specific plugins or swap deps and use the lib it uses, `lodash`, in many cases. If you're interested I can do a PR.

Thanks.

**Comment by jdalton** [comment]
Now that [lodash v3]https://github.com/lodash/lodash/releases/tag/3.0.0) is out I'll tackle the conversion over the weekend.

**Comment by ericelliott** [comment]
Awesome! =)
