### ISSUE TITLE
Increase lodash version from 4.13.1 to 4.17.5 to avoid a small vulnerability

### ISSUE THREAD

**Issue by BenSower** [ericelliott/bunyan-request-logger#22]
Not a big problem, just wanted to let you know:
https://snyk.io/vuln/npm:lodash:20180130

**Comment by ericelliott** [comment]
Published security updates as bunyan-request-logger@2.0.0

Major because we dropped support for very old node version (0.12)

**Comment by pixelchutes** [comment]
Looks like this issue can now be closed. Thanks @ericelliott
